### ISSUE TITLE
[功能请求]

### ISSUE THREAD

**Issue by ZhangLinShui** [Keychron/qmk_firmware#148]
### Feature Request Type

- [ ] Core functionality
- [X] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [X] New behavior

### Description

我的遇到的问题是 我来回切换layer 以后 不知道当前所在的layer
所以我的需求是 通过某种方式 告知我 当前的layer
以下是我的思考和建议
Q3 Pro 左侧 四个按键 M1、M2、M3、M4 我设置为修改Layer 我希望 我按下对应的键后 led 灯能常量 以表示当前所在的layer
也可以增加 小屏幕 其中显示当前layer

**Comment by KeychronMacro** [comment]
屏幕的话还没计划去做，但是用led灯指示层状态是可以的，不过需要自己在源码上修改，因为这个功能个性化太强，所以没有做这个功能。
