### ISSUE TITLE
[Feature Request]  Add support for Vial-qmk on the k7 pro

### ISSUE THREAD

**Issue by gozes** [Keychron/qmk_firmware#155]
### Feature Request Type

- [X] Core functionality
- [X] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

it would be great if you could add https://github.com/vial-kb/vial-qmk support on the k7 pro :) will this be something that is doable?

by the look at the code in the k7 pro folder it maybe possible with minor tweaks I think but I have never done anything with qmk so I'm unsure

**Comment by lokher** [comment]
Sorry, we have no plan on vial qmk, but you can refer to this link to check: https://github.com/adophoxia/vial-qmk/tree/vial-keychron-bluetooth-playground/

I am not sure whether it works
