### ISSUE TITLE
[Feature Request] Release files for K10 Pro ISO layout

### ISSUE THREAD

**Issue by DayTF** [Keychron/qmk_firmware#168]
### Feature Request Type

- [X] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

I cannot find the via json configuration files in the repository for the K10 Pro ISO. 
I was expecting to find them here: https://github.com/Keychron/qmk_firmware/tree/bluetooth_playground/keyboards/keychron/k10_pro/via_json

Please, do tell if i'm not looking at the right spot.

**Comment by altarofwisdom-perso** [comment]
Yes, only ANSI seems to be available, and I have warnings when trying to load that into usevia (native under Monterey)
<img width="658" alt="Screenshot 2023-09-22 at 19 06 26" src="https://github.com/Keychron/qmk_firmware/assets/122935531/3a21ed7a-d4c2-40ea-8b94-1ecba676f22f">
