### ISSUE TITLE
Keychron K Pro Series Bluetooth Firmware?

### ISSUE THREAD

**Issue by fofpgf** [Keychron/qmk_firmware#169]
Are there source codes of Keychron K Pro Series Bluetooth Firmware?
Thank you.

**Comment by nnhanndakara** [comment]
The source code for Keychron's K series keyboards, as well as basically all other keyboards that are currently advertised as supporting QMK/VIA, but that may not have been submitted upstream yet, are in the `bluetooth_playground` branch of the repository located [here](https://github.com/Keychron/qmk_firmware/tree/bluetooth_playground/keyboards/keychron).

**Comment by lokher** [comment]
Sorry, the Bluetooth firmware source code cannot be opened due to the NDA signed with the chip factory.

**Comment by fofpgf** [comment]
> The source code for Keychron's K series keyboards, as well as basically all other keyboards that are currently advertised as supporting QMK/VIA, but that may not have been submitted upstream yet, are in the `bluetooth_playground` branch of the repository located [here](https://github.com/Keychron/qmk_firmware/tree/bluetooth_playground/keyboards/keychron).

Ok. Got it. Thank you.

**Comment by focus-mt** [comment]
> Sorry, the Bluetooth firmware source code cannot be opened due to the NDA signed with the chip factory.

Ok. Got it. Thank you.

But the keyboard name is shown as **_"Keychron K1 Pro"_** when I update version 1.32 on this URL:https://www.keychron.com/pages/keychron-k-pro-series-bluetooth-firmware.
Before the update it was shown as **_Keychron K1 Pro_**.

**Comment by focus-mt** [comment]
> Sorry, the Bluetooth firmware source code cannot be opened due to the NDA signed with the chip factory.

Ok. Got it. Thank you.

But the keyboard name is shown as "Keychron K1 Pro" when I update to version 1.32 on this URL:https://www.keychron.com/pages/keychron-k-pro-series-bluetooth-firmware.
Before the update it was shown as Keychron K1 Pro.
Now it just looks a little bit curious. Is there any bluetooth firmware update plan for Keychron K Pro Series?

**Comment by fofpgf** [comment]
> Sorry, the Bluetooth firmware source code cannot be opened due to the NDA signed with the chip factory.

Ok. Got it. Thank you.

But the keyboard name is shown as **_"Keychron K1 Pro"_** when I update to version 1.32 on this URL:https://www.keychron.com/pages/keychron-k-pro-series-bluetooth-firmware.
Before the update it was shown as **_Keychron K1 Pro_**.
Now it just looks a little bit curious. Is there any bluetooth firmware update plan for Keychron K Pro Series?

**Comment by sencagri** [comment]
> Sorry, the Bluetooth firmware source code cannot be opened due to the NDA signed with the chip factory.

So why you are advertising as QMK supported?

**Comment by svenjacobs** [comment]
> Sorry, the Bluetooth firmware source code cannot be opened due to the NDA signed with the chip factory.

@lokher I'm sorry, but you advertise these keyboards with QMK functionality, which is an open source firmware, but then cannot release the source code for these keyboards? 🤔

**Comment by lokher** [comment]
> > Sorry, the Bluetooth firmware source code cannot be opened due to the NDA signed with the chip factory.
> 
> @lokher I'm sorry, but you advertise these keyboards with QMK functionality, which is an open source firmware, but then cannot release the source code for these keyboards? 🤔

The source code of main MCU is opened, almost all QMK functionalities are runned on it.
