### ISSUE TITLE
[Feature Request] publish k15 pro files

### ISSUE THREAD

**Issue by rayslinky** [Keychron/qmk_firmware#177]
### Feature Request Type

- [X] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

Please publish (or point me to) the files for the k15 pro.

**Comment by lokher** [comment]
The source code has been pushed and merged.
