### ISSUE TITLE
[Bug] VIA can't fetch V3 definitions for Keyboard K8 Pro V3 pre-compiled firmware; received invalid protocol version from device

### ISSUE THREAD

**Issue by NovaViper** [Keychron/qmk_firmware#179]
### Describe the Bug

I downloaded the [precompiled firmware for the RGB Ansi version of the K8 Pro that's in the repo](https://github.com/Keychron/qmk_firmware/blob/bluetooth_playground/keyboards/keychron/k8_pro/firmware/keychron_k8_pro_ansi_rgb_via.bin) and flashed it but whenever I open VIA now, I get these errors when loading up the keyboard in the program (on the webapp and on desktop)
```
19:15:51.654
Fetching v3 definition failed
Device: Keychron Keychron K8 Pro
Vid: 0x3434
Pid: 0x0280

19:16:00.895
The device must be opened first.
Device: Keychron Keychron K8 Pro
Vid: 0x3434
Pid: 0x0280

19:16:00.972
Received invalid protocol version from device
Device: Keychron Keychron K8 Pro
Vid: 0x3434
Pid: 0x0280
```

### Keyboard Used

Keychron K8 Pro

### Operating System

NixOS 23.11 (unstable)

### qmk doctor Output
I used the precompiled firmware but also decided to try and manually compile the firmware
```
❯ qmk doctor
Ψ QMK Doctor is checking your environment.
Ψ CLI version: 1.1.2
Ψ QMK home: /home/novaviper/qmk_firmware
Ψ Detected Linux (NixOS 23.11 (Tapir)).
Ψ Git branch: bluetooth_playground
Ψ Repo version: 0.14.29
Ψ - Latest bluetooth_playground: 2023-09-11 15:54:14 +0800 (00af20f690) -- Merge pull request #167 from slabua/k11_pro_via_json_fix
Ψ - Latest upstream/master: None
Ψ - Latest upstream/develop: None
Ψ - Common ancestor with upstream/master: None
Ψ - Common ancestor with upstream/develop: None
Ψ All dependencies are installed.
Ψ Found arm-none-eabi-gcc version 12.2.1
Ψ Found avr-gcc version 8.5.0
Ψ Found avrdude version 7.2
Ψ Found dfu-programmer version 0.7.2
Ψ Found dfu-util version 0.11
Ψ Submodules are up to date.
Ψ Submodule status:
Ψ - lib/chibios: 2022-09-18 10:01:17 +0000 --  (0e9d558b5)
Ψ - lib/chibios-contrib: 2022-10-03 18:09:41 +0200 --  (bb8356fb)
Ψ - lib/googletest: 2021-06-11 06:37:43 -0700 --  (e2239ee6)
Ψ - lib/lufa: 2022-08-26 12:09:55 +1000 --  (549b97320)
Ψ - lib/vusb: 2022-06-13 09:18:17 +1000 --  (819dbc1)
Ψ - lib/printf: 2022-06-29 23:59:58 +0300 --  (c2e3b4e)
Ψ - lib/pico-sdk: 2022-09-19 18:02:44 +0200 --  (8d56ea3)
Ψ - lib/lvgl: 2022-04-11 04:44:53 -0600 --  (e19410f8)
Ψ QMK is ready to go

```

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

### Other keyboard-related software installed

VIA

### Additional Context

I also tried to manually compile the firmware but then VIA wouldn't pick up on the keyboard at all because it didn't provide the via json needed for the keyboard when I manually built it.

**Comment by lokher** [comment]
Only VIA v2 json is merged to VIA github, v3 json need to be manaully loaded. 
The json file is in ([via_json](https://github.com/Keychron/qmk_firmware/tree/bluetooth_playground/keyboards/keychron/k8_pro/via_json)) 

Please refer to below link to use it:
https://www.keychron.com/blogs/archived/how-to-use-via-to-program-your-keyboard

**Comment by NovaViper** [comment]
Hey I'm closing the issue since this has to be done manually
