### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by ahaha-yu** [Keychron/qmk_firmware#206]
### Feature Request Type

- [X] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

Request to add k3pro support

**Comment by lokher** [comment]
K3 Pro is in `bluetooth_playground` or `wireless_playground` branch
