### ISSUE TITLE
i need V1 MAX source code !!!

### ISSUE THREAD

**Issue by DeGrey** [Keychron/qmk_firmware#208]
### Issue Description

when is available about  keychron v1 max source code

**Comment by adophoxia** [comment]
[Ahem...](https://github.com/Keychron/qmk_firmware/tree/wireless_playground/keyboards/keychron/v1_max)

**Comment by DeGrey** [comment]
well, thanks a lot.
it is certanly v1 max code.but it can't compile because lack of following files:
```
qmk_firmware/lib/printf/src/printf/*
qmk_firmware/lib/lufa/LUFA/*
qmk_firmware/lib/chibios/*
```
i copied them from qmk master branch. and compile has passed.

**Comment by lokher** [comment]
> well, thanks a lot. it is certanly v1 max code.but it can't compile because lack of following files:
> 
> ```
> qmk_firmware/lib/printf/src/printf/*
> qmk_firmware/lib/lufa/LUFA/*
> qmk_firmware/lib/chibios/*
> ```
> 
> i copied them from qmk master branch. and compile has passed.

Did you run "git submodule update"?

**Comment by DeGrey** [comment]
yes
i've tried update submodule and build default keymap flash to my keyboard.
It's work normally.
Thanks for your reply.
