### ISSUE TITLE
[Feature Request] Add K3 Max Source Code

### ISSUE THREAD

**Issue by loofkid** [Keychron/qmk_firmware#215]
### Feature Request Type

- [X] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

K3 Max source isn't included.

**Comment by bbucko** [comment]
I was told by the support team that they expect the source code to be released in Jan/Feb.

**Comment by loofkid** [comment]
Awesome, thanks for letting me know!

**Comment by lokher** [comment]
Done
https://github.com/Keychron/qmk_firmware/tree/wireless_playground/keyboards/keychron/k3_max
