### ISSUE TITLE
[Bug] BT audio stutter on windows11 with K2 Pro

### ISSUE THREAD

**Issue by thomaslagies** [Keychron/qmk_firmware#218]
### Describe the Bug

Whenever I use the Keychron K2 Pro via Bluetooth on my windows 11 PC, I get audio stutters with my BT Headset.
The Keychron is the only device, that causes this. Other bluetooth devices are fine to connect with windows. 

I'm running the latest windows update (23H2 Windows 11 Pro - Build 22631.3007) and the latest keychron firmware was flashed (~https://www.keychron.com/pages/firmware-for-k2-version-2~ https://www.keychron.com/blogs/archived/k2-pro-factory-reset-and-firmware-flash) 
I just flashed not because the keyboard was not working, but because the audio stutter. It seems like it did not change anything.

I don't have these issues on my Mac M1 for example. 
My Phone also works fine with Headset and Keyboard connected.

### Keyboard Used

Keychron K2 Pro QMK

### Link to product page (if applicable)

https://www.keychron.com/products/keychron-k2-pro-qmk-via-wireless-mechanical-keyboard

### Operating System

Windows 11 Pro

### qmk doctor Output

 qmk doctor
Ψ QMK Doctor is checking your environment.
Ψ CLI version: 1.1.2
Ψ QMK home: C:/Users/Thomas/qmk_firmware
Ψ Detected Windows 10 (10.0.22631).
Ψ QMK MSYS version: 1.8.0
Ψ Userspace enabled: False
Ψ Git branch: master
Ψ Repo version: 0.23.5
Ψ - Latest master: 2024-01-14 06:07:59 +0000 (dcc47ea31b) -- Add Proteus67 keyboard (#22439)
Ψ - Latest upstream/master: 2024-01-14 06:07:59 +0000 (dcc47ea31b) -- Add Proteus67 keyboard (#22439)
Ψ - Latest upstream/develop: None
Ψ - Common ancestor with upstream/master: 2024-01-14 06:07:59 +0000 (dcc47ea31b) -- Add Proteus67 keyboard (#22439)
Ψ - Common ancestor with upstream/develop: None
Ψ All dependencies are installed.
Ψ Found arm-none-eabi-gcc version 12.2.0
Ψ Found avr-gcc version 12.2.0
⚠ We do not recommend avr-gcc newer than 8. Downgrading to 8.x is recommended.
Ψ Found avrdude version 7.0
Ψ Found dfu-programmer version 1.1.0
Ψ Found dfu-util version 0.11
Ψ Submodules are up to date.
Ψ Submodule status:
Ψ - lib/chibios: 2023-04-15 13:48:04 +0000 --  (11edb1610)
Ψ - lib/chibios-contrib: 2023-07-17 11:39:05 +0200 --  (da78eb37)
Ψ - lib/googletest: 2021-06-11 06:37:43 -0700 --  (e2239ee6)
Ψ - lib/lufa: 2022-08-26 12:09:55 +1000 --  (549b97320)
Ψ - lib/vusb: 2022-06-13 09:18:17 +1000 --  (819dbc1)
Ψ - lib/printf: 2022-06-29 23:59:58 +0300 --  (c2e3b4e)
Ψ - lib/pico-sdk: 2023-02-12 20:19:37 +0100 --  (a3398d8)
Ψ - lib/lvgl: 2022-04-11 04:44:53 -0600 --  (e19410f8)
Ψ QMK is ready to go, but minor problems were found

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

### Other keyboard-related software installed

Logitech Software for mouse

**Comment by lokher** [comment]
Trye this bluetooth firmware
[keychron_ckbt51_01.32-2.zip](https://github.com/Keychron/qmk_firmware/files/13970722/keychron_ckbt51_01.32-2.zip)

**Comment by adophoxia** [comment]
@thomaslagies, you mention you have a **Keychron K2 Pro**, but in the 2nd paragraph of this post, you mentioned you flashed firmware for the [Keychron K2 V2](https://www.keychron.com/pages/firmware-for-k2-version-2), aka, the regular K2. Is that right?

**Comment by thomaslagies** [comment]
Sorry, I posted the wrong link.
https://www.keychron.com/blogs/archived/k2-pro-factory-reset-and-firmware-flash
I will update the description.

**Comment by thomaslagies** [comment]
> Trye this bluetooth firmware [keychron_ckbt51_01.32-2.zip](https://github.com/Keychron/qmk_firmware/files/13970722/keychron_ckbt51_01.32-2.zip)

Will try this the other day. Thanks

**Comment by thomaslagies** [comment]
This seems to have fixed all the stutter!
Thanks mate. 
Also I found the post about audio stutter on the keychron website (via reddit)
How could I miss that for almost half a year?!
