### ISSUE TITLE
how to repurpose the os dip switch k8 pro

### ISSUE THREAD

**Issue by Dialgatrainer02** [Keychron/qmk_firmware#227]
### Issue Description

i use linux and i have the dip switch set to win/android. i also have custom layers and removed the mac os ones from keymap.c. how to i make the dip switch change to one of my custom layers and not attempt to switch to mac os then fail. 
when i do switch it to mac os if i try to press tab a few of the buttons blink red. 

i tried setting my dip_switch_update_user() in my keymap.c and i get compilation errors to about factory_test.o

**Comment by sjthearts** [comment]
rename dip_switch_update_user to orig_dip_switch_update_user in factory_test.c and rebuild.

**Comment by Dialgatrainer02** [comment]
tried this and still errors it even errors when i comment out the whole function in factory test.c 
im running qmk clean each time
i have a k8 pro
