### ISSUE TITLE
K10 pro + manual firmware build = Bluetooth not working?

### ISSUE THREAD

**Issue by anenviousguest** [Keychron/qmk_firmware#229]
### Issue Description

Hi folks, K10 Pro owner here.

I have a K10 Pro running on Windows 10, with a stock firmware and wanted to configure VIA macros which uses [delays](https://github.com/the-via/releases/issues/24) whose support has been added to VIA long ago.

Sample macro code could look like:

```
{KC_LGUI}{500}mycoolsoftware{500}{KC_ENT}
```

However, after pairing VIA with my keyboard and trying to edit the macro code, I've got an error message from VIA saying that delays are not supported with current version of firmware.

Never mind, I built the firmware from the source code, trying both [wireless_playground](https://github.com/Keychron/qmk_firmware/tree/wireless_playground) as well as [bluetooth_playground](https://github.com/Keychron/qmk_firmware/tree/bluetooth_playground) branches and using this command to build:

```
make keychron/k10_pro/ansi/white:via
```

On its own, the firmware builds just fine, and also I can successfully flash it with QMK Toolbox. Also macro starts supporting delays, yay! 

![image](https://github.com/Keychron/qmk_firmware/assets/8439575/7520489c-7243-46bb-b3b2-216f17b76907)

_…However!!!..._

Seems like the firmware built from those branches does not fully support Bluetooth functionality - I still can pair the device anyhow, but the keyboard is not recognized as a _keyboard_ any longer, and the keystrokes do not work - tried with both `*playground` branches listed above, after deleting previously paired bluetooth device definitions. After flashing to the stock firmware, Bluetooth is working fine again. 

I researched the issues on this repo and found few mentions (e.g. [here](https://github.com/Keychron/qmk_firmware/issues/169#issuecomment-1712819387)) that Bluetooth-related code is not published due to it being NDA'ed.

**Questions:** 
1. Does that really mean that the firmware built from the source code for K10 Pro is never going to support Bluetooth?
2. Or am I missing something? What is then the way to get the Bluetooth working for the firmware built from the source code (from wireless- or bluetooth playground branches)?

Seems like a bummer to be forced to choose between Bluetooth and latest VIA support 😅

Thanks.

**Comment by anenviousguest** [comment]
hi @lokher , do you have an insight into the questions above? Thank you.

**Comment by lokher** [comment]
Can you try the firmware https://github.com/Keychron/qmk_firmware/tree/bluetooth_playground/keyboards/keychron/k10_pro/firmware

**Comment by anenviousguest** [comment]
@lokher yeah, i actually found that the keyboard works over Bluetooth, even with a firmware built from sources - looks like the old  device definition got somehow stuck in the Windows settings, I had to remove the old device from the Windows BT settings and it started working...

**Comment by anenviousguest** [comment]
BT actually works.
