### ISSUE TITLE
[Feature Request] Add to readme.md information about NEW_SAFE_RANGE

### ISSUE THREAD

**Issue by paat** [Keychron/qmk_firmware#240]
### Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [X] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

I used online tutorials to customize my Q3 Pro within keymap.c.
When defining new new keycode enums I started with KC_MYKEY = SAFE_RANGE
But I did not realize that Keychron added their own enums and defined NEW_SAFE_RANGE. So I spent hours debugging why bluetooth is not working with my custom build.

I would have been helpful to put information about NEW_SAFE_RANGE in readme.md.

**Comment by exstntlmsnthrp** [comment]
I think this may have at least some peripheral relationship to #217 in that keychron has been a little vague in sharing details regarding Bluetooth and QMK programming. Thus limiting benefits of upstream QMK and making it more difficult for users to figure out. As they seem reluctant to add other information, I'd not hold my breath waiting for this.
