### ISSUE TITLE
When wireless_playground branch will be merged to master? (V1 MAX)

### ISSUE THREAD

**Issue by RDSlaughter** [Keychron/qmk_firmware#249]
### Issue Description

**Hi everyone.**
I bought the Keychron v1 Max  2 weeks ago. Various errors are received when building QMK firmware with the current branch. I encountered other errors such as WS2812 pin definitions etc and I fixed them one by one manually by removing the function definitions of some of them (which is not a good way but could not find any resource about it). I was able to build successfully and define custom caps lock and layer rgb indicators. But I could not use the charge indicator in any way.  There are things that are out of date and constantly cause errors.  And I think the current branch does not match with the ready to use .bin file in the official website for v1 max. I think we need to merge the **wireless_playground** branch to master.

**Comment by alex-vg** [comment]
see https://github.com/Keychron/qmk_firmware/issues/242

**Comment by lokher** [comment]
Did you build with keychron fork and `wireless_playground` branch? 
`wireless_playground` won't be merged to QMK upstream due to it make much core modification and they don't accept it.

**Comment by RDSlaughter** [comment]
> Did you build with keychron fork and `wireless_playground` branch? `wireless_playground` won't be merged to QMK upstream due to it make much core modification and they don't accept it.

I did, i do not think it is ready to use.  At least for v1 max
