### ISSUE TITLE
Cannot add the mappings I need in my new keychron k3 pro

### ISSUE THREAD

**Issue by mjacobus** [Keychron/qmk_firmware#251]
### Issue Description

Hey there. I just received my new k3 pro.

I was able to start mapping my keys but I felt some features were missing. I am not sure that is a limitation of the keyboard or the via interface.

First off, I am surprised there is only 4 layers. Can I have more?

Second, I did not find the hold-tap behavior. For instance, I want my ";" to behave like "ctrl" when I hold it, but ";" when I tap it. Is that supported?

Is via including all available features for that keyboard, or can I get more custom going bear QMK? I have zero experience with it, and I would not go down that path if that is not going to solve the above for me anyways.

Thank you in advance.

**Comment by lokher** [comment]
You need to modify the code for your customization, start from qmk docs: 
https://docs.qmk.fm/#/

And use `wireless_playground` branch from keychron fork:
https://github.com/Keychron/qmk_firmware/tree/wireless_playground/keyboards/keychron/k3_pro

Go to https://discord.com/invite/HAYbRrTsjN if you need help

**Comment by mjacobus** [comment]
Thank you, @lokher.
