### ISSUE TITLE
[Bug] Q6 MAX via.json file from official site missing one RGB effect

### ISSUE THREAD

**Issue by Bodyash** [Keychron/qmk_firmware#253]
### Describe the Bug

 I downloaded json file from official website (v1.0) - and it has this line duplicated:
```
                  ["Cycle Out In", 8],
                  ["Cycle Out In", 8],
```

While here: https://github.com/Keychron/qmk_firmware/blob/wireless_playground/keyboards/keychron/q6_max/via_json/q6_max_ansi_encoder.json

It has 

```               
                  ["Cycle Out In", 8],
                  ["Cycle Out In Dual", 9],
```

### Link to product page (if applicable)

https://www.keychron.com/products/keychron-q6-max-qmk-via-wireless-custom-mechanical-keyboard?_pos=4&_psq=q6+max&_ss=e&_v=1.0

### Operating System

ArchLinux

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

**Comment by lokher** [comment]
Thank you for pointing it out, it will be fixed soon
