### ISSUE TITLE
Remove use of user level qmk callbacks

### ISSUE THREAD

**Issue by nskobelevs** [Keychron/qmk_firmware#258]
### Issue Description

Some of the Bluetooth code defines `_user` specific qmk callbacks, more specifically:

`led_matrix_indicators_user`, `rgb_matrix_indicators_user` and `dip_switch_update_user`  in [factory_test.c](https://github.com/Keychron/qmk_firmware/blob/613719b66db811d4795c87eb5efb99f4fe7eed97/keyboards/keychron/bluetooth/factory_test.c)
and `led_matrix_indicators_user` and `rgb_matrix_indicators_user` in [indicator.c](https://github.com/Keychron/qmk_firmware/blob/613719b66db811d4795c87eb5efb99f4fe7eed97/keyboards/keychron/bluetooth/indicator.c).

I think there's also a non standard handling of `dip_switch_update_user` in (among others) [q3_pro.c](https://github.com/Keychron/qmk_firmware/blob/bluetooth_playground/keyboards/keychron/q3_pro/q3_pro.c#L66-L74). (I would expect the user callback to be called first before modifying the default layer)

Having these as user level means if someone wants to define their own ones, they'd need to go and modify the existing firmware to avoid multiple definitions. 

Is there any reason these need to be at the user level and not at the keyboard level? Could these be renamed and called explicitly from the `_kb` callbacks?

I'm happy to open up a PR if this is okay to change ^

**Comment by PeterMortensen** [comment]
Agreed. E.g., it makes it more difficult and more complex to have common code between wired-only and wireless Keychron keyboards.
