### ISSUE TITLE
Q12 Max Firmware 

### ISSUE THREAD

**Issue by 1-lost-cause** [Keychron/qmk_firmware#263]
### Feature Request Type

- [X] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

When can we expect to see the firmware for the Q12 Max added to wireless playground?

**Comment by lokher** [comment]
Added.
https://github.com/Keychron/qmk_firmware/tree/wireless_playground/keyboards/keychron/q12_max
