### ISSUE TITLE
K11 Max Firmware

### ISSUE THREAD

**Issue by boobay** [Keychron/qmk_firmware#264]
### Feature Request Type

- [X] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

When will the k11 max code be available under wireless playground? :)

**Comment by choenig** [comment]
I'm really interested in this as well. 

/br
christian

**Comment by jnolck** [comment]
Me two. I just got the k11 max like two weeks ago and had good scare the night I got it. I compiled and flashed the k11 pro firmware onto it and thought I bricked it.

**Comment by boobay** [comment]
Customer support says the source code will be available within a few weeks in the wireless_playground branch.

**Comment by choenig** [comment]
It looks like it landed :)

https://github.com/Keychron/qmk_firmware/tree/wireless_playground/keyboards/keychron/k11_max
