### ISSUE TITLE
[Bug] Unable to build K3 Max because of 'function with qualified void return type called'

### ISSUE THREAD

**Issue by bbucko** [Keychron/qmk_firmware#272]
### Describe the Bug

I think that commit b6d42d84d2726e3976508dac48f937b2502f03e8 broke the build for K3 Max. When running 'make keychron/k3_max/ansi/rgb:default' on a fresh repo i'm getting this error:

`
tmk_core/protocol/chibios/usb_driver.c:128:9: error: function with qualified void return type called [-Werror]
         endpoint->report_storage->reset_report(endpoint->report_storage->reports);
         ^
tmk_core/protocol/chibios/usb_driver.c: In function 'usb_endpoint_in_suspend_cb':
tmk_core/protocol/chibios/usb_driver.c:151:9: error: function with qualified void return type called [-Werror]
         endpoint->report_storage->reset_report(endpoint->report_storage->reports);
         ^
tmk_core/protocol/chibios/usb_driver.c: In function 'usb_endpoint_in_tx_complete_cb':
tmk_core/protocol/chibios/usb_driver.c:206:13: error: function with qualified void return type called [-Werror]
             endpoint->report_storage->set_report(endpoint->report_storage->reports, buffer, n);
             ^
cc1: all warnings being treated as errors
`

When building on dda14805a125cd6a11dec4856c9f9e3b7da5fcdf everything is fine.

### Keyboard Used

k3_max/ansi

### Operating System

mac

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

**Comment by bbucko** [comment]
Broken toolchain on my Mac.

**Comment by bilogic** [comment]
@bbucko 

can i ask 

1. if you used to wireless_playground branch?
2. were the build steps as per QMK's default or something different?

thanks!

**Comment by bbucko** [comment]
Issue was caused by a different gcc installed on my Mac. I reinstalled the packages and the issue went away.

**Comment by bilogic** [comment]
cool thanks let me try to build and flash my K3 Max
