### ISSUE TITLE
Publish sources for Q3 Max ISO

### ISSUE THREAD

**Issue by inkfarer** [Keychron/qmk_firmware#273]
I'd like to request the source files for the [ISO version](https://www.keychron.com/collections/keychron-q-max-series-keyboard/products/keychron-q3-max-qmk-via-wireless-custom-mechanical-keyboard-iso-layout-collection) of the Q3 Max. I've found that only the ANSI version has sources available as of now.

**Comment by DottieUnderwood** [comment]
Same for Q6 Max ISO. The keyboard is shipping but the source is nowhere to be found :-(

**Comment by mvbentes** [comment]
Same for K13 Pro ISO. I need to be able to set `TAPPING_TERM` for mod tap and that cannot be accomplished via the launcher.
Both the `bluetooth_playground` and the `wireless_playground` branches only contain the ANSI source.

**Comment by lokher** [comment]
Added.
https://github.com/Keychron/qmk_firmware/tree/wireless_playground/keyboards/keychron/q3_max/iso_encoder

**Comment by lokher** [comment]
> Same for Q6 Max ISO. The keyboard is shipping but the source is nowhere to be found :-(
https://github.com/Keychron/qmk_firmware/tree/wireless_playground/keyboards/keychron/q6_max/iso_encoder

**Comment by lokher** [comment]
> Same for K13 Pro ISO. I need to be able to set `TAPPING_TERM` for mod tap and that cannot be accomplished via the launcher. Both the `bluetooth_playground` and the `wireless_playground` branches only contain the ANSI source.

https://github.com/Keychron/qmk_firmware/tree/wireless_playground/keyboards/keychron/k13_pro/iso
