### ISSUE TITLE
V4 Max Source Code missing?

### ISSUE THREAD

**Issue by raeffs** [Keychron/qmk_firmware#276]
Where can I find the source code for the V4 Max model?

The "wireless_playground" branch only contains the source code for all the other V Max models: https://github.com/Keychron/qmk_firmware/tree/wireless_playground/keyboards/keychron

**Comment by lokher** [comment]
Added.
https://github.com/Keychron/qmk_firmware/tree/wireless_playground/keyboards/keychron/v4_max
