### ISSUE TITLE
[Feature Request] Q13 Pro Support

### ISSUE THREAD

**Issue by JSelvaraj** [Keychron/qmk_firmware#279]
### Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [X] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

Hi I saw you have a closed PR with support for Q13 Pro keyboard here: https://github.com/Keychron/qmk_firmware/pull/184 
Would you be able to take another look at merging in the changes for it?

**Comment by lokher** [comment]
it't in `wireless_playground` branch
https://github.com/Keychron/qmk_firmware/tree/wireless_playground/keyboards/keychron/q13_pro

**Comment by JSelvaraj** [comment]
Thanks!
