### ISSUE TITLE
Please provide the source code of q15 max firmware.

### ISSUE THREAD

**Issue by seonwons** [Keychron/qmk_firmware#291]
### Issue Description

I would be very grateful if you could provide us the source code of q15 max firmware as soon as possible.

**Comment by pedrorq** [comment]
+1

**Comment by skanev** [comment]
+1

**Comment by MinaDarsh** [comment]
+1

Please release firmware before shipping out boards, makes everyone happier.

**Comment by lokher** [comment]
Added.
https://github.com/Keychron/qmk_firmware/tree/wireless_playground/keyboards/keychron/q15_max

**Comment by seonwons** [comment]
Thank you very much. You will be blessed. :)
