### ISSUE TITLE
[Feature Request] K5 Max ISO

### ISSUE THREAD

**Issue by braca** [Keychron/qmk_firmware#294]
### Feature Request Type

- [ ] Core functionality
- [X] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

Is it possible to add the [K5 Max ISO](https://www.keychron.com/products/keychron-k5-max-qmk-wireless-custom-mechanical-keyboard-iso-layout-collection)?
There is already a K5 Pro ISO but the Max version is not available

**Comment by lokher** [comment]
Added.
https://github.com/Keychron/qmk_firmware/tree/wireless_playground/keyboards/keychron/k5_max/iso
