### ISSUE TITLE
[Source code] K15 Max RGB

### ISSUE THREAD

**Issue by gauravjuvekar** [Keychron/qmk_firmware#299]
Please provide the source code for K15 Max RGB

https://www.keychron.com/products/keychron-k15-max-alice-layout-qmk-wireless-custom-mechanical-keyboard?variant=41569533526105

https://github.com/qmk/qmk_firmware/issues/24085

**Comment by susch19** [comment]
The code has been added with this commit a few hours ago [abefc1d](https://github.com/Keychron/qmk_firmware/commit/abefc1d4a6be3ca70fec42288d5f30896ba70a81)

**Comment by gauravjuvekar** [comment]
Perfect, thanks!
