### ISSUE TITLE
[Feature Request] K8 Max Source Code

### ISSUE THREAD

**Issue by venengaandrew** [Keychron/qmk_firmware#323]
### Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

any chance we could get the source code for the K8 Max?

**Comment by lokher** [comment]
Added.
https://github.com/Keychron/qmk_firmware/tree/wireless_playground/keyboards/keychron/k8_max

**Comment by venengaandrew** [comment]
Thank you!

Quick issue, flashing the RGB ANSI profile to my K8 Max makes keys 1, Q, and A unresponsive. 

Is there any debug information I could provide for more clarity?

This was tested running both: 
make keychron/k8_max/ansi/rgb:default and flashing using QMK Toolbox
make keychron/k8_max/ansi/rgb:default:flash

**Comment by lokher** [comment]
> Thank you!
> 
> Quick issue, flashing the RGB ANSI profile to my K8 Max makes keys 1, Q, and A unresponsive.
> 
> Is there any debug information I could provide for more clarity?
> 
> This was tested running both: make keychron/k8_max/ansi/rgb:default and flashing using QMK Toolbox make keychron/k8_max/ansi/rgb:default:flash

Thanks for your feedfback, it's fixed now,  please pull and compile again.
