### ISSUE TITLE
Publish source code for Q10 Max ISO

### ISSUE THREAD

**Issue by smazh** [Keychron/qmk_firmware#333]
### Issue Description

I'd like to request source files for the [ISO variant](https://www.keychron.uk/products/keychron-q10-max-alice-layout-qmk-custom-mechanical-keyboard-iso-layout-collection) of the Q10 Max please. The ANSI version has sources available at https://github.com/Keychron/qmk_firmware/tree/wireless_playground/keyboards/keychron/q10_max but the iso_encoder appears to be missing.

**Comment by lokher** [comment]
Added
https://github.com/Keychron/qmk_firmware/tree/wireless_playground/keyboards/keychron/q10_max/iso_encoder

**Comment by smazh** [comment]
Thank you! For everyone's benefit correct link for Q10 max iso: https://github.com/Keychron/qmk_firmware/tree/wireless_playground/keyboards/keychron/q10_max/iso_encoder

**Comment by lokher** [comment]
link updated too.
